require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CactusController do

  # This should return the minimal set of attributes required to create a valid
  # Cactu. As you add validations to Cactu, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CactusController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cactus as @cactus" do
      cactu = Cactu.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cactus).should eq([cactu])
    end
  end

  describe "GET show" do
    it "assigns the requested cactu as @cactu" do
      cactu = Cactu.create! valid_attributes
      get :show, {:id => cactu.to_param}, valid_session
      assigns(:cactu).should eq(cactu)
    end
  end

  describe "GET new" do
    it "assigns a new cactu as @cactu" do
      get :new, {}, valid_session
      assigns(:cactu).should be_a_new(Cactu)
    end
  end

  describe "GET edit" do
    it "assigns the requested cactu as @cactu" do
      cactu = Cactu.create! valid_attributes
      get :edit, {:id => cactu.to_param}, valid_session
      assigns(:cactu).should eq(cactu)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cactu" do
        expect {
          post :create, {:cactu => valid_attributes}, valid_session
        }.to change(Cactu, :count).by(1)
      end

      it "assigns a newly created cactu as @cactu" do
        post :create, {:cactu => valid_attributes}, valid_session
        assigns(:cactu).should be_a(Cactu)
        assigns(:cactu).should be_persisted
      end

      it "redirects to the created cactu" do
        post :create, {:cactu => valid_attributes}, valid_session
        response.should redirect_to(Cactu.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cactu as @cactu" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cactu.any_instance.stub(:save).and_return(false)
        post :create, {:cactu => {  }}, valid_session
        assigns(:cactu).should be_a_new(Cactu)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cactu.any_instance.stub(:save).and_return(false)
        post :create, {:cactu => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cactu" do
        cactu = Cactu.create! valid_attributes
        # Assuming there are no other cactus in the database, this
        # specifies that the Cactu created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cactu.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => cactu.to_param, :cactu => { "these" => "params" }}, valid_session
      end

      it "assigns the requested cactu as @cactu" do
        cactu = Cactu.create! valid_attributes
        put :update, {:id => cactu.to_param, :cactu => valid_attributes}, valid_session
        assigns(:cactu).should eq(cactu)
      end

      it "redirects to the cactu" do
        cactu = Cactu.create! valid_attributes
        put :update, {:id => cactu.to_param, :cactu => valid_attributes}, valid_session
        response.should redirect_to(cactu)
      end
    end

    describe "with invalid params" do
      it "assigns the cactu as @cactu" do
        cactu = Cactu.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cactu.any_instance.stub(:save).and_return(false)
        put :update, {:id => cactu.to_param, :cactu => {  }}, valid_session
        assigns(:cactu).should eq(cactu)
      end

      it "re-renders the 'edit' template" do
        cactu = Cactu.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cactu.any_instance.stub(:save).and_return(false)
        put :update, {:id => cactu.to_param, :cactu => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cactu" do
      cactu = Cactu.create! valid_attributes
      expect {
        delete :destroy, {:id => cactu.to_param}, valid_session
      }.to change(Cactu, :count).by(-1)
    end

    it "redirects to the cactus list" do
      cactu = Cactu.create! valid_attributes
      delete :destroy, {:id => cactu.to_param}, valid_session
      response.should redirect_to(cactus_url)
    end
  end

end
